name: build-libcxx

on:
  push:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: none


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ll/libcxx.bc"
          body: "LLVM IR for `libcxx` and `libcxxabi`"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.0.${{ github.run_number }}

      - name: Install required dependencies
        # ubuntu-latest already has many of the packages we want installed. See
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        run: |
          sudo apt update
          sudo apt-get install -y \
            ninja-build \
            libgtest-dev \
            libfmt-dev \
            libboost-all-dev
          sudo ./.github/scripts/update-alternatives-llvm.sh 11 20
          go get github.com/SRI-CSL/gllvm/cmd/...

      - name: Build
        run: make
