name: build-libcxx

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: insufficientlycaffeinated/alpine-bob:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          artifacts: "ll/libcxx.bc,ll/libcxx.tar.gz"
          body: "LLVM IR for `libcxx` and `libcxxabi`"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master
          tag: v0.0.${{ github.run_number }}
